Feature(#34) - Create TextArea component
TyMSpa-2/front pull request #39
Opened 2023-03-02 16:49 UTC by avilalte

Changes

- Created TextArea component.
- Created useInputSize hook to make TextArea height change dynamically with content.

Checklist

- [x] Commit messages follow the standards
- [x] I linked the related issue
- [x] I added reviewers
- [x] PR name follows the standards
- [x] I reviewed my PR

2023-03-05 16:37 UTC, Qweffy requested changes

2023-03-05 16:37 UTC, Qweffy commented on src/components/inputs/TextArea/TextAreaWrapper.styled.ts
> +  width: 328px;
Do we have variables for this?

2023-03-05 16:37 UTC, Qweffy commented on src/components/inputs/TextArea/TextArea.styled.ts
> +  font-weight: 400;
do we have variables for this?

2023-03-07 01:13 UTC, avilalte commented on src/components/inputs/TextArea/TextAreaWrapper.styled.ts
> +  width: 328px;
We don't. I can create new variables for these properties for the next PR.

2023-03-10 01:29 UTC, merged