Feature(#42) Create EditQuestion button
TyMSpa-2/front pull request #43
Opened 2023-03-22 00:30 UTC by avilalte

Changes

- Created EditQuestion button component for the admin's backoffice. 
- Deleted old placeholder for the Home page and replaced it with new "Under Construction" page.
- Small refactor for CollapsibleButton and new variable for the GlobalStyles.

Checklist

- [x] Commit messages follow the standards
- [x] I linked the related issue
- [x] I added reviewers
- [x] PR name follows the standards
- [x] I reviewed my PR

2023-03-22 16:34 UTC, Qweffy requested changes

2023-03-22 16:34 UTC, Qweffy commented on src/components/UnderConstruction/UnderConstruction.tsx
> +
can we move all the styles in the styles file?

2023-03-22 22:57 UTC, avilalte commented on src/components/UnderConstruction/UnderConstruction.tsx
> +
Yes, I'll do that and push the changes in a bit.

2023-03-23 15:23 UTC, Qweffy commented
LGTM

2023-03-23 15:39 UTC, merged